services:
  frontend:
    build:
      context: frontend
      args:
        VITE_BACKEND_URL: "${VITE_BACKEND_URL:-http://localhost:8080}"
    ports:
      - "${FRONTEND_PORT:-80}:80"
    environment:
      GIN_MODE: "release"
  backend:
    build:
      context: backend
    ports:
      - "${BACKEND_PORT:-8080}:8080"